---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  MY_ENV_VAR: 'U0VDUkVUCg=='
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: my-image:v0.0.1
          env:
            - name: MY_ENV_VAR
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: MY_ENV_VAR
