---
apiVersion: v1
kind: Pod
metadata:
  name: liveness-readiness-probe
spec:
  containers:
    - name: liveness-readiness-probe
      image: nginx
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /readiness
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
