name: Guard Test

on:
  push:
  workflow_dispatch:

jobs:
  kubevious_validation_cli:
    runs-on: ubuntu-latest
    name: Kubevious CLI Validation Run
    steps:
      - name: Test environment
        run: |
          pwd; ls -lha && echo "Running tests on the ${{ github.workspace }}"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Custom tests
        run: |
          pwd; ls -lha && echo "Running custom tests on the ${{ github.workspace }}"
          npm install -g kubevious
          set -x
          kubevious guard ./yaml/app.yaml
          kubevious guard ./yaml/app-livenessProbe.yaml
          kubevious guard ./yaml/app-readinessProbe.yaml
          kubevious guard ./yaml/app-volumeMounts.yaml
          kubevious guard ./yaml/app-cronjob.yaml
          kubevious guard ./yaml/app-job.yaml
          kubevious guard ./yaml/app-multicontainer.yaml
          kubevious guard ./yaml/app-resources.yaml
          kubevious guard ./yaml/app-secret-env.yaml

  kubevious_validation_docker:
    runs-on: ubuntu-latest
    name: Kubevious Docker Validation Run
    steps:
      - name: Test environment
        run: |
          pwd; ls -lha && echo "Running tests on the ${{ github.workspace }}"
          which docker

      - name: Checkout
        uses: actions/checkout@v3

      - name: Test manifests with Docker
        uses: docker://kubevious/cli:latest
        with:
          args: -v ${{ github.workspace }}:/src
