name: Guard Test

on: [push]

jobs:
  checkout_repo:
    runs-on: ubuntu-latest
    container:
      image: kubevious/cli:latest
    name: Checkout repo
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  kubevious_validation:
    runs-on: ubuntu-latest
    needs: checkout_repo
    container:
      image: kubevious/cli:latest
    name: Kubevious CLI Validation Run
    steps:
      - name: Test manifests
        run: |
          kubevious guard ./yaml/app.yaml
          kubevious guard ./yaml/app-livenessProbe.yaml
          kubevious guard ./yaml/app-readinessProbe.yaml
          kubevious guard ./yaml/app-volumeMounts.yaml
          kubevious guard ./yaml/app-cronjob.yaml
          kubevious guard ./yaml/app-job.yaml
          kubevious guard ./yaml/app-multicontainer.yaml
          kubevious guard ./yaml/app-resources.yaml
          kubevious guard ./yaml/app-secret-env.yaml
