name: Guard Test

on:
  push:
  workflow_dispatch:

jobs:
  checkout_repo:
    runs-on: ubuntu-latest
    name: Checkout repo
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  kubevious_validation:
    runs-on: ubuntu-latest
    needs: checkout_repo
    name: Kubevious Docker Validation Run
    steps:
      - name: Test manifests with Docker
        uses: docker://kubevious/cli:latest
        with:
          args: -v ${{ github.workspace }}:/src

  kubevious_validation_custom:
    runs-on: ubuntu-latest
    needs: checkout_repo
    name: Kubevious CLI Validation Run
    steps:
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Custom tests
        run: |
          pwd; ls -lha && echo "Running custom tests on the ${{ github.workspace }}"
          npm install -g kubevious
          set -x
          kubevious guard ./yaml/app.yaml
          kubevious guard ./yaml/app-livenessProbe.yaml
          kubevious guard ./yaml/app-readinessProbe.yaml
          kubevious guard ./yaml/app-volumeMounts.yaml
          kubevious guard ./yaml/app-cronjob.yaml
          kubevious guard ./yaml/app-job.yaml
          kubevious guard ./yaml/app-multicontainer.yaml
          kubevious guard ./yaml/app-resources.yaml
          kubevious guard ./yaml/app-secret-env.yaml
