name: Guard Test

on: 
  push:
  workflow_dispatch:

jobs:
  checkout_repo:
    runs-on: ubuntu-latest
    name: Checkout repo
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  kubevious_validation:
    runs-on: ubuntu-latest
    needs: checkout_repo
    name: Kubevious CLI Validation Run
    steps:
      - name: Test manifests with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: kubevious/cli:latest
          run: |
            pwd; ls -lh 
            set -x
            ls -lha /src && ls -lha /src/*
            find / -type f -name 'app.yaml' 2>/dev/null
            # kubevious guard ./yaml/app.yaml
            # kubevious guard ./yaml/app-livenessProbe.yaml
            # kubevious guard ./yaml/app-readinessProbe.yaml
            # kubevious guard ./yaml/app-volumeMounts.yaml
            # kubevious guard ./yaml/app-cronjob.yaml
            # kubevious guard ./yaml/app-job.yaml
            # kubevious guard ./yaml/app-multicontainer.yaml
            # kubevious guard ./yaml/app-resources.yaml
            # kubevious guard ./yaml/app-secret-env.yaml
